# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

r:
  - 3.2.3
  - release
  - devel

repos:
  docker: https://r.docker.stat.auckland.ac.nz
